export const LOAD_COMPONENT = "LOAD_COMPONENT";
export const LOAD_COMPONENT_SUCCESS = "LOAD_COMPONENT:SUCCESS";
export const LOAD_COMPONENT_ERROR = "LOAD_COMPONENT:ERROR";

export const DELETE_COMPONENT = "DELETE_COMPONENT";
export const DELETE_COMPONENT_SUCCESS = "DELETE_COMPONENT:SUCCESS";
export const DELETE_COMPONENT_ERROR = "DELETE_COMPONENT:ERROR";

export const UPDATE_COMPONENT = "UPDATE_COMPONENT";
export const UPDATE_COMPONENT_SUCCESS = "UPDATE_COMPONENT:SUCCESS";
export const UPDATE_COMPONENT_ERROR = "UPDATE_COMPONENT:ERROR";

export const ADD_COMPONENT = "ADD_COMPONENT";
export const ADD_COMPONENT_SUCCESS = "ADD_COMPONENT:SUCCESS";
export const ADD_COMPONENT_ERROR = "ADD_COMPONENT:ERROR";
