export const LOAD_USER = "LOAD_USER";
export const LOAD_USER_SUCCESS = "LOAD_USER:SUCCESS";
export const LOAD_USER_ERROR = "LOAD_USER:ERROR";

export const DELETE_USER = "DELETE_USER";

export const UPDATE_USER_PRODUCTS = "UPDATE_USER_PRODUCTS";
export const UPDATE_USER_PRODUCTS_SUCCESS = "UPDATE_USER_PRODUCTS:SUCCESS";
export const UPDATE_USER_PRODUCTS_ERROR = "UPDATE_USER_PRODUCTS:ERROR";

