export const LOAD_USER = "LOAD_USER";
export const LOAD_USER_SUCCESS = "LOAD_USER:SUCCESS";
export const LOAD_USER_ERROR = "LOAD_USER:ERROR";

export const DELETE_USER = "DELETE_USER";

export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_USER_SUCCESS = "UPDATE_USER:SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER:ERROR";

export const ADD_USER = "ADD_USER";
export const ADD_USER_SUCCESS = "ADD_USER:SUCCESS";
export const ADD_USER_ERROR = "ADD_USER:ERROR";

