export const LOAD_RECIPES = "LOAD_RECIPES";
export const LOAD_RECIPES_SUCCESS = "LOAD_RECIPES:SUCCESS";
export const LOAD_RECIPES_ERROR = "LOAD_RECIPES:ERROR";

export const DELETE_RECIPE = "DELETE_RECIPE";
