export const LOAD_PRODUCTS = "LOAD_PRODUCTS";
export const LOAD_PRODUCTS_SUCCESS = "LOAD_PRODUCTS:SUCCESS";
export const LOAD_PRODUCTS_ERROR = "LOAD_PRODUCTS:ERROR";

export const ADD_PRODUCT = "ADD_PRODUCT";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT:SUCCESS";
export const ADD_PRODUCT_ERROR = "ADD_PRODUCT:ERROR";

export const EDIT_PRODUCT = "EDIT_PRODUCT";
export const EDIT_PRODUCT_SUCCESS = "EDIT_PRODUCT:SUCCESS";
export const EDIT_PRODUCT_ERROR = "EDIT_PRODUCT:ERROR";

export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT:SUCCESS";
export const DELETE_PRODUCT_ERROR = "DELETE_PRODUCT:ERROR";



