export const LOAD_DIET= "LOAD_DIET";
export const LOAD_DIET_SUCCESS = "LOAD_DIET:SUCCESS";
export const LOAD_DIET_ERROR = "LOAD_DIET:ERROR";

export const DELETE_DIET = "DELETE_DIET";
export const DELETE_DIET_SUCCESS = "DELETE_DIET:SUCCESS";
export const DELETE_DIET_ERROR = "DELETE_DIET:ERROR";

export const UPDATE_DIET = "UPDATE_DIET";
export const UPDATE_DIET_SUCCESS = "UPDATE_DIET:SUCCESS";
export const UPDATE_DIET_ERROR = "UPDATE_DIET:ERROR";

export const ADD_DIET = "ADD_DIET";
export const ADD_DIET_SUCCESS = "ADD_DIET:SUCCESS";
export const ADD_DIET_ERROR = "ADD_DIET:ERROR";
